# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'SDWebImage', '~> 5.0'
pod 'AFNetworking', '~> 4.0'
pod 'MJExtension'
pod 'SVProgressHUD'
pod 'pop'
target 'BaiSiProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BaiSiProject

  target 'BaiSiProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BaiSiProjectUITests' do
    # Pods for testing
  end

end
