# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '8.0'
pod 'SDWebImage', '~> 5.0'
target 'FuncTest01' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FuncTest01

  target 'FuncTest01Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FuncTest01UITests' do
    # Pods for testing
  end

end
